import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const manifest = JSON.parse(readFileSync("package.json", "utf8"));
if (manifest.license !== "Apache-2.0") throw new Error("Studio must publish under Apache-2.0.");
if (manifest.repository?.url !== "git+https://github.com/nylorun/harness.git" || manifest.repository?.directory !== "studio") throw new Error("Studio must reference its public source directory.");
if (manifest.bugs !== "https://github.com/nylorun/harness/issues") throw new Error("Studio must reference the public issue tracker.");
if (manifest.dependencies?.["@nylorun/create-agent"] !== undefined) throw new Error("Studio must not depend on Create Agent.");
const cache = mkdtempSync(join(tmpdir(), "nylo-studio-pack-"));
const output = execFileSync(process.platform === "win32" ? "npm.cmd" : "npm", ["pack", "--json", "--dry-run", "--ignore-scripts"], { encoding: "utf8", env: { ...process.env, npm_config_cache: cache } });
rmSync(cache, { recursive: true, force: true });
const files = JSON.parse(output)[0].files.map((entry) => entry.path);
for (const required of ["package.json", "README.md", "LICENSE", "dist/cli.js", "dist/host.js", "dist/web/index.html", "dist/web/nylo-studio.config.json"]) if (!files.includes(required)) throw new Error(`Missing tarball file: ${required}`);
if (files.includes("dist/ui.js")) throw new Error("Legacy inline Studio UI must not be packaged.");
console.log(`Studio tarball allowlist passed (${files.length} files).`);
