import { type FormEvent, type ReactNode, useEffect, useMemo, useState } from "react";
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import { HttpAgent } from "@ag-ui/client";
import { AssistantRuntimeProvider } from "@assistant-ui/react";
import { useAgUiRuntime } from "@assistant-ui/react-ag-ui";
import { Activity, CirclePlus, LoaderCircle, SendHorizontal, ServerOff } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Tabs as TabsPrimitive } from "radix-ui";
import { loadBrowserStudioConfig } from "./config";
import { activitiesForEvents, eventLabel, eventSummary, type CanonicalEvent } from "./event-presentation";

type AgentManifest = Readonly<{ protocolVersion: number; id: string; name: string; description: string; capabilities: readonly string[]; requirements?: Record<string, boolean>; model: { provider: string; id: string }; harness: { name: string; version: string; manifest: { middleware?: readonly { id: string }[] } }; endpoints: { agUi: string; sessions: string }; records?: { path: string } }>;
type Discovery = Readonly<{ protocolVersion: number; agents: readonly { id: string; manifestUrl: string }[] }>;
type SessionSummary = Readonly<{ session: string; status: string; startedAt: number; endedAt?: number; events: number }>;
type PendingInteraction = Readonly<{ id: string; kind: "approval" | "response"; prompt: string }>;
type ChatMessage = Readonly<{ id: string; role: string; content: string }>;
type Connection = Readonly<{ status: "Connecting" | "Running" | "Offline"; url?: string; agents: readonly AgentManifest[] }>;

function endpoint(base: string, value: string): string { return new URL(value, `${base}/`).toString(); }
function shortId(id: string): string { return id.length > 12 ? `${id.slice(0, 8)}…${id.slice(-4)}` : id; }
function date(value?: number): string { return value === undefined ? "—" : new Date(value).toLocaleString(); }
function pretty(value: unknown): string { try { return JSON.stringify(value, null, 2); } catch { return "Unserializable value"; } }

function useConnection(): Connection {
  const [connection, setConnection] = useState<Connection>({ status: "Connecting", agents: [] });
  useEffect(() => {
    let disposed = false;
    const refresh = async (): Promise<void> => {
      try {
        const config = await loadBrowserStudioConfig();
        if (config.agentServerUrl === undefined) throw new Error("No Agent Server URL configured.");
        const response = await fetch(endpoint(config.agentServerUrl, "/v1/agents"), { cache: "no-store" });
        if (!response.ok) throw new Error(`Agent Server returned ${response.status}.`);
        const discovery = await response.json() as Discovery;
        if (discovery.protocolVersion !== 1 || !Array.isArray(discovery.agents)) throw new Error("Unsupported Studio discovery document.");
        const agents = await Promise.all(discovery.agents.map(async (entry) => {
          const manifest = await fetch(endpoint(config.agentServerUrl!, entry.manifestUrl), { cache: "no-store" });
          if (!manifest.ok) throw new Error(`Manifest for ${entry.id} returned ${manifest.status}.`);
          const raw = await manifest.json() as AgentManifest;
          return { ...raw, endpoints: { agUi: endpoint(config.agentServerUrl!, raw.endpoints.agUi), sessions: endpoint(config.agentServerUrl!, raw.endpoints.sessions) } };
        }));
        if (!disposed) setConnection({ status: "Running", url: config.agentServerUrl, agents });
      } catch {
        if (!disposed) setConnection((previous) => ({ status: "Offline", url: previous.url, agents: previous.agents }));
      }
    };
    void refresh();
    const timer = window.setInterval(() => void refresh(), 2_000);
    return () => { disposed = true; window.clearInterval(timer); };
  }, []);
  return connection;
}

function Empty({ title, detail }: Readonly<{ title: string; detail: string }>) { return <div className="grid min-h-52 place-items-center rounded-lg border border-dashed p-8 text-center"><div><h2 className="font-medium">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{detail}</p></div></div>; }
function Card({ title, children }: Readonly<{ title: string; children: ReactNode }>) { return <section className="rounded-xl border bg-card p-5 shadow-sm"><h2 className="text-sm font-semibold">{title}</h2><div className="mt-4">{children}</div></section>; }
function Tokens({ values }: Readonly<{ values: readonly string[] }>) { return values.length === 0 ? <p className="text-sm text-muted-foreground">None declared</p> : <div className="flex flex-wrap gap-2">{values.map((value) => <Badge key={value} variant="secondary">{value}</Badge>)}</div>; }

function TopBar({ connection }: Readonly<{ connection: Connection }>) {
  const location = useLocation(); const navigate = useNavigate(); const agentId = location.pathname.match(/^\/agents\/([^/]+)/u)?.[1]; const running = connection.status === "Running"; const state = running ? "bg-emerald-500" : connection.status === "Connecting" ? "bg-amber-500" : "bg-muted-foreground";
  return <header className="fixed inset-x-0 top-0 z-40 flex h-16 items-center border-b bg-background/95 px-5 backdrop-blur"><Link to="/" className="mr-6 flex items-center gap-2 font-semibold tracking-tight"><img src="/brand/nylorun-mark.svg" alt="" className="size-7" />Nylorun Studio</Link><p className="hidden text-sm text-muted-foreground sm:block">{agentId === undefined ? "Agent server" : `Agent: ${agentId}`}</p><div className="ml-auto flex items-center gap-3"><Button variant="outline" size="icon" disabled={!running || agentId === undefined} onClick={() => navigate(`/agents/${agentId}/sessions/${crypto.randomUUID()}`)}><CirclePlus className="size-4" /><span className="sr-only">New session</span></Button><span className={`size-2 rounded-full ${state}`} />{connection.status === "Connecting" ? <LoaderCircle className="size-3 animate-spin" /> : running ? <Activity className="size-3" /> : <ServerOff className="size-3" />}<span className="text-sm">{connection.status}</span></div></header>;
}

function AgentList({ connection }: Readonly<{ connection: Connection }>) { return <main className="mx-auto max-w-6xl p-6"><div className="mb-7"><h1 className="text-2xl font-semibold tracking-tight">Agents</h1><p className="mt-1 text-sm text-muted-foreground">Studio reads the manifests exposed by your local agent server.</p></div>{connection.status !== "Running" ? <Empty title="Agent server is offline" detail="Start your Hono host, then Studio will discover its agent manifests." /> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{connection.agents.map((agent) => <Link key={agent.id} to={`/agents/${encodeURIComponent(agent.id)}`} className="rounded-xl border bg-card p-5 shadow-sm transition-colors hover:bg-muted/50"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{agent.name}</h2><p className="mt-1 font-mono text-xs text-muted-foreground">{agent.id}</p></div><Badge variant="outline">{agent.model.provider}</Badge></div><p className="mt-4 text-sm text-muted-foreground">{agent.description}</p><div className="mt-4"><Tokens values={agent.capabilities} /></div></Link>)}</div>}</main>; }

function AgentDashboard({ connection }: Readonly<{ connection: Connection }>) {
  const { agentId = "" } = useParams(); const navigate = useNavigate(); const agent = connection.agents.find((entry) => entry.id === agentId); const [sessions, setSessions] = useState<readonly SessionSummary[]>([]);
  useEffect(() => { if (connection.url === undefined || agent === undefined) return; let cancelled = false; const load = async (): Promise<void> => { const response = await fetch(endpoint(connection.url!, agent.endpoints.sessions), { cache: "no-store" }); if (response.ok && !cancelled) setSessions((await response.json() as { sessions: SessionSummary[] }).sessions); }; void load(); const timer = window.setInterval(() => void load(), 2_000); return () => { cancelled = true; window.clearInterval(timer); }; }, [connection.url, agent]);
  if (agent === undefined) return <main className="p-6"><Empty title="Agent not found" detail="Return to the agent list and select an available manifest." /></main>;
  const middleware = agent.harness.manifest.middleware ?? [];
  return <main className="mx-auto max-w-6xl p-6"><Link to="/" className="text-sm text-muted-foreground hover:text-foreground">← All agents</Link><div className="mt-4 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 className="text-2xl font-semibold tracking-tight">{agent.name}</h1><p className="mt-1 text-sm text-muted-foreground">{agent.description}</p></div><div className="flex gap-2"><Badge>{agent.model.provider}</Badge><Badge variant="outline">{agent.model.id}</Badge></div></div><TabsPrimitive.Root defaultValue="manifest" className="mt-7"><TabsPrimitive.List className="flex h-10 items-end gap-6 border-b"><TabsPrimitive.Trigger value="manifest" className="border-b-2 border-transparent px-0 pb-3 text-sm data-[state=active]:border-primary">Manifest</TabsPrimitive.Trigger><TabsPrimitive.Trigger value="sessions" className="border-b-2 border-transparent px-0 pb-3 text-sm data-[state=active]:border-primary">Sessions</TabsPrimitive.Trigger></TabsPrimitive.List><TabsPrimitive.Content value="manifest" className="mt-5 space-y-4"><div className="grid gap-4 md:grid-cols-2"><Card title="Capabilities"><Tokens values={agent.capabilities} /></Card><Card title="Harness"><dl className="grid gap-3 text-sm"><div><dt className="text-muted-foreground">Package</dt><dd>{agent.harness.name} {agent.harness.version}</dd></div><div><dt className="text-muted-foreground">Middleware</dt><dd><Tokens values={middleware.map((entry) => entry.id)} /></dd></div></dl></Card></div><Card title="Requirements"><Tokens values={Object.entries(agent.requirements ?? {}).filter(([, enabled]) => enabled).map(([name]) => name)} /><p className="mt-4 text-xs text-muted-foreground">Records: {agent.records?.path ?? "not reported"}</p></Card></TabsPrimitive.Content><TabsPrimitive.Content value="sessions" className="mt-5"><div className="rounded-lg border"><Table><TableHeader><TableRow><TableHead>ID</TableHead><TableHead>Status</TableHead><TableHead>Started</TableHead><TableHead>Events</TableHead></TableRow></TableHeader><TableBody>{sessions.length === 0 ? <TableRow><TableCell colSpan={4} className="h-24 text-center text-muted-foreground">No sessions yet.</TableCell></TableRow> : sessions.map((session) => <TableRow key={session.session} className="cursor-pointer" onClick={() => navigate(`/agents/${agent.id}/sessions/${session.session}`)}><TableCell className="font-mono text-xs">{shortId(session.session)}</TableCell><TableCell><Badge variant="secondary">{session.status}</Badge></TableCell><TableCell>{date(session.startedAt)}</TableCell><TableCell>{session.events}</TableCell></TableRow>)}</TableBody></Table></div></TabsPrimitive.Content></TabsPrimitive.Root></main>;
}

function ActivityFeed({ events }: Readonly<{ events: readonly CanonicalEvent[] }>) { const activities = activitiesForEvents(events); return <section className="mb-4 rounded-lg border bg-card p-3"><div className="mb-2 flex justify-between"><p className="text-sm font-medium">Run activity</p><p className="text-xs text-muted-foreground">Canonical events</p></div>{activities.length === 0 ? <p className="text-sm text-muted-foreground">Activity will appear when the agent runs.</p> : <ol className="space-y-2">{activities.map((activity) => <li key={activity.id} className="rounded-md border px-3 py-2 text-sm"><div className="flex justify-between gap-3"><span className="font-medium">{activity.title}</span><span className="text-xs capitalize text-muted-foreground">{activity.state}</span></div><p className="mt-1 text-xs text-muted-foreground">{activity.detail}</p></li>)}</ol>}</section>; }
function Runtime({ url, children }: Readonly<{ url: string; children: ReactNode }>) { const runner = useMemo(() => new HttpAgent({ url }), [url]); const runtime = useAgUiRuntime({ agent: runner }); return <AssistantRuntimeProvider runtime={runtime}>{children}</AssistantRuntimeProvider>; }

function Chat({ agent, sessionId, events }: Readonly<{ agent: AgentManifest; sessionId: string; events: readonly CanonicalEvent[] }>) {
  const [messages, setMessages] = useState<readonly ChatMessage[]>([]); const [input, setInput] = useState(""); const [pending, setPending] = useState<PendingInteraction | undefined>(); const [sending, setSending] = useState(false); const [error, setError] = useState<string | undefined>();
  useEffect(() => { let cancelled = false; const load = async (): Promise<void> => { const history = await fetch(`${agent.endpoints.agUi.replace(/\/$/u, "")}/sessions/${encodeURIComponent(sessionId)}`, { cache: "no-store" }); if (history.ok && !cancelled) setMessages((await history.json() as { messages: ChatMessage[] }).messages); const summary = await fetch(`${agent.endpoints.sessions.replace(/\/$/u, "")}/${encodeURIComponent(sessionId)}`, { cache: "no-store" }); if (summary.ok && !cancelled) setPending((await summary.json() as { pending_interaction?: PendingInteraction }).pending_interaction); }; void load(); const timer = window.setInterval(() => void load(), 1_000); return () => { cancelled = true; window.clearInterval(timer); }; }, [agent, sessionId]);
  const send = async (event: FormEvent): Promise<void> => { event.preventDefault(); if (!input.trim() || sending) return; const text = input.trim(); setInput(""); setSending(true); setError(undefined); setMessages((current) => [...current, { id: crypto.randomUUID(), role: "user", content: text }]); try { const runner = new HttpAgent({ url: agent.endpoints.agUi, threadId: sessionId }); runner.addMessage({ id: crypto.randomUUID(), role: "user", content: text } as never); await runner.runAgent({ runId: crypto.randomUUID() }, { onNewMessage: ({ message }) => { const value = message as unknown as { id?: string; role?: string; content?: unknown }; setMessages((current) => [...current, { id: value.id ?? crypto.randomUUID(), role: value.role ?? "assistant", content: typeof value.content === "string" ? value.content : pretty(value.content) }]); } }); } catch (cause) { setError(cause instanceof Error ? cause.message : "Agent request failed."); } finally { setSending(false); } };
  const interact = async (approved: boolean): Promise<void> => { if (pending === undefined) return; setSending(true); try { const response = await fetch(`${agent.endpoints.sessions.replace(/\/$/u, "")}/${encodeURIComponent(sessionId)}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ interaction: { id: pending.id, kind: "approval", approved } }) }); if (!response.ok) throw new Error(`Approval returned ${response.status}.`); setPending(undefined); } catch (cause) { setError(cause instanceof Error ? cause.message : "Approval failed."); } finally { setSending(false); } };
  return <div className="flex h-[calc(100vh-11rem)] min-h-96 flex-col border"><ScrollArea className="min-h-0 flex-1 p-5"><ActivityFeed events={events} /><div className="space-y-4">{messages.map((message) => <article key={message.id} className={`max-w-3xl rounded-lg px-4 py-3 text-sm ${message.role === "user" ? "ml-auto bg-primary text-primary-foreground" : "bg-muted"}`}><p className="mb-1 text-xs opacity-70">{message.role}</p><p className="whitespace-pre-wrap">{message.content}</p></article>)}{pending !== undefined && <section className="rounded-lg border border-amber-400/50 bg-amber-50 p-4 text-sm"><p className="font-medium">Approval required</p><p className="mt-1">{pending.prompt}</p><div className="mt-3 flex gap-2"><Button size="sm" onClick={() => void interact(true)}>Approve</Button><Button size="sm" variant="outline" onClick={() => void interact(false)}>Deny</Button></div></section>}{error !== undefined && <p role="alert" className="text-sm text-destructive">{error}</p>}</div></ScrollArea><form onSubmit={send} className="flex gap-2 border-t p-3"><Input value={input} onChange={(event) => setInput(event.target.value)} disabled={sending || pending !== undefined} placeholder="Message the agent…" /><Button type="submit" size="icon" disabled={sending || pending !== undefined || !input.trim()}><SendHorizontal className="size-4" /></Button></form></div>;
}

function SessionDashboard({ connection }: Readonly<{ connection: Connection }>) {
  const { agentId = "", sessionId = "" } = useParams(); const agent = connection.agents.find((entry) => entry.id === agentId); const [events, setEvents] = useState<readonly CanonicalEvent[]>([]); const [selected, setSelected] = useState<CanonicalEvent | undefined>();
  useEffect(() => { if (agent === undefined) return; let cancelled = false; const load = async (): Promise<void> => { const response = await fetch(`${agent.endpoints.sessions.replace(/\/$/u, "")}/${encodeURIComponent(sessionId)}/events?after=0&limit=1000`, { cache: "no-store" }); if (response.ok && !cancelled) setEvents((await response.json() as { events: CanonicalEvent[] }).events); }; void load(); const timer = window.setInterval(() => void load(), 1_000); return () => { cancelled = true; window.clearInterval(timer); }; }, [agent, sessionId]);
  if (agent === undefined) return <main className="p-6"><Empty title="Agent not found" detail="Return to the agent list and select an available manifest." /></main>;
  return <Runtime url={agent.endpoints.agUi}><main className="mx-auto max-w-6xl p-6"><Link to={`/agents/${agent.id}`} className="text-sm text-muted-foreground hover:text-foreground">← {agent.name}</Link><h1 className="mt-3 text-xl font-semibold">Session {shortId(sessionId)}</h1><TabsPrimitive.Root defaultValue="chat" className="mt-5"><TabsPrimitive.List className="flex h-10 items-end gap-6 border-b"><TabsPrimitive.Trigger value="chat" className="border-b-2 border-transparent px-0 pb-3 text-sm data-[state=active]:border-primary">Chat</TabsPrimitive.Trigger><TabsPrimitive.Trigger value="events" className="border-b-2 border-transparent px-0 pb-3 text-sm data-[state=active]:border-primary">Events</TabsPrimitive.Trigger></TabsPrimitive.List><TabsPrimitive.Content value="chat" className="mt-4"><Chat agent={agent} sessionId={sessionId} events={events} /></TabsPrimitive.Content><TabsPrimitive.Content value="events" className="mt-4"><div className="rounded-lg border"><Table><TableHeader><TableRow><TableHead>Event</TableHead><TableHead>Summary</TableHead></TableRow></TableHeader><TableBody>{events.map((event) => <TableRow key={event.seq} className="cursor-pointer" onClick={() => setSelected(event)}><TableCell><Badge variant="secondary">{eventLabel(event)}</Badge></TableCell><TableCell className="max-w-2xl truncate text-xs text-muted-foreground">{eventSummary(event)}</TableCell></TableRow>)}</TableBody></Table></div></TabsPrimitive.Content></TabsPrimitive.Root></main><Sheet modal={false} open={selected !== undefined} onOpenChange={(open) => !open && setSelected(undefined)}><SheetContent showOverlay={false}><SheetHeader><SheetTitle>{selected === undefined ? "Event" : eventLabel(selected)}</SheetTitle><SheetDescription>Canonical event details</SheetDescription></SheetHeader>{selected !== undefined && <ScrollArea className="min-h-0 flex-1 px-4 pb-6"><pre className="overflow-auto rounded bg-muted p-3 text-xs">{pretty(selected)}</pre></ScrollArea>}</SheetContent></Sheet></Runtime>;
}

function Shell() { const connection = useConnection(); return <><TopBar connection={connection} /><div className="pt-16"><Routes><Route path="/" element={<AgentList connection={connection} />} /><Route path="/agents/:agentId" element={<AgentDashboard connection={connection} />} /><Route path="/agents/:agentId/sessions/:sessionId" element={<SessionDashboard connection={connection} />} /></Routes></div></>; }
export default function App() { return <BrowserRouter><Shell /></BrowserRouter>; }
