import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { readFile } from "node:fs/promises";
const [repo, runtimePort, studioPort, open, project] = process.argv.slice(2);
const { startStudio } = await import(pathToFileURL(join(repo, "studio/dist/index.js")).href);
const { serverKey } = JSON.parse(await readFile(join(project, ".nylorun/local-credentials.json"), "utf8"));
const studio = await startStudio({ runtimeUrl: `http://127.0.0.1:${runtimePort}`, serverKey, port: Number(studioPort), open: open === "true" });
console.log(`Studio on ${studio.address}`);
process.once("SIGINT", () => void studio.close());
process.once("SIGTERM", () => void studio.close());
